# fly.toml app configuration file generated for phuc-veyt-challenge on 2023-11-25T23:40:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phuc-veyt-challenge"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
